In [1]:
import numpy as np

a = np.matrix([
    [1,2,3,4],
    [5,6,7,8]
])

#### transpose

In [2]:
a.T

matrix([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

#### inverse

In [3]:
a.I

matrix([[-5.50000000e-01,  2.50000000e-01],
        [-2.25000000e-01,  1.25000000e-01],
        [ 1.00000000e-01, -2.08166817e-17],
        [ 4.25000000e-01, -1.25000000e-01]])

#### multiply must obey matrix rules (shape must align)

In [4]:
b = np.matrix([1,2])
a*b

ValueError: shapes (2,4) and (1,2) not aligned: 4 (dim 1) != 1 (dim 0)

In [6]:
c = np.matrix([
    [1],
    [2],
    [3],
    [4]
])
a*c

matrix([[30],
        [70]])

> More operations can be found in the ***numpy.linalg*** subpackage.