[NumPy](http://www.numpy.org/)

> For any heavy computation involving arrays, use the NumPy library.

In [3]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

b = a + 1
print(b)

c = a*2
print(c)

d = a**2
print(d)

[1 2 3 4]
[2 3 4 5]
[2 4 6 8]
[ 1  4  9 16]


#### for math ops on numpy array, please use numpy math ops

In [5]:
# using the standard math lib will pop error
import math
math.sqrt(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [6]:
e = np.sqrt(a)
print(e)

[1.         1.41421356 1.73205081 2.        ]


> One extremely notable aspect of NumPy is the manner in which it extends Python’s list
indexing functionality—especially with multidimensional arrays.

In [7]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8.0],
    [0.9,10,1.1,120]
])

In [10]:
print(x[:,1])

[ 2.  6. 10.]


In [11]:
print(x[:2,:3])

[[1. 2. 3.]
 [5. 6. 7.]]


### numpy.where return the coordinates of the entries satisfying the condition

In [12]:
print(np.where(x>3))

(array([0, 1, 1, 1, 1, 2, 2]), array([3, 0, 1, 2, 3, 1, 3]))


#### use numpy.where to make a mask

In [13]:
print(np.where(x>3,True, False))

[[False False False  True]
 [ True  True  True  True]
 [False  True False  True]]
